language: python

env:
    - TOX_ENV=py35-django110
    - TOX_ENV=py34-django110
    - TOX_ENV=py27-django110
    - TOX_ENV=py35-django19
    - TOX_ENV=py34-django19
    - TOX_ENV=py27-django19
    - TOX_ENV=py35-django18
    - TOX_ENV=py34-django18
    - TOX_ENV=py27-django18

install:
  - pip install tox coveralls

script:
    - tox -e $TOX_ENV
    - coverage report -m

after_success:
    - coveralls