language: python
services:
  - redis-server
python:
    - "3.6"
    - "3.7"
    - "3.8"
env:
    - TOX_ENV=django2220
    - TOX_ENV=django318
    - TOX_ENV=django320
install:
  - pip install tox coveralls
script:
    - tox -e $TOX_ENV
    - coverage report -m
after_success:
    - coveralls
