language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"

env:
    - TOX_ENV=django226
    - TOX_ENV=django202

install:
  - pip install tox coveralls

script:
    - tox -e $TOX_ENV
    - coverage report -m

after_success:
    - coveralls
