language: python
services:
  - redis-server
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"
env:
    - TOX_ENV=django2226
    - TOX_ENV=django3211
    - TOX_ENV=django403
install:
  - pip install tox coveralls
script:
    - tox -e $TOX_ENV
    - coverage report -m
after_success:
    - coveralls
