language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"

env:
    - TOX_ENV=django19
    - TOX_ENV=django18
    
install:
  - pip install tox coveralls

script:
    - tox -e $TOX_ENV
    - coverage report -m

after_success:
    - coveralls