# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('translation_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationentry',
            name='language',
            field=models.CharField(db_index=True, max_length=7, verbose_name='admin-translation_entry-language-label'),
        ),
    ]
