# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('translation_manager', '0002_auto_20160920_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationbackup',
            options={'ordering': ('-created',), 'verbose_name': 'Admin-translation_backup-singular',
                     'verbose_name_plural': 'Admin-translation_backup-plural'},
        ),
        migrations.AlterModelOptions(
            name='translationentry',
            options={'ordering': ('original',), 'permissions': (('load', 'admin-translation_entry-load-from-po'),),
                     'verbose_name': 'Admin-translation_entry-singular',
                     'verbose_name_plural': 'Admin-translation_entry-plural'},
        ),
    ]
