# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation_manager', '0005_auto_20170915_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyTranslationEntry',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('translation_manager.translationentry',),
        ),
        migrations.RenameField(
            model_name='remotetranslationentry',
            old_name='remote_changed',
            new_name='changed',
        ),
        migrations.RemoveField(
            model_name='remotetranslationentry',
            name='remote_translation',
        ),
        migrations.AddField(
            model_name='remotetranslationentry',
            name='translation',
            field=models.TextField(blank=True, verbose_name='admin-remote_translation_entry-remote_translation-label'),
        ),
        migrations.AlterField(
            model_name='remotetranslationentry',
            name='translation_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remote_translation_entry', to='translation_manager.TranslationEntry'),
        ),
    ]
