# Generated by Django 2.2.9 on 2020-01-20 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation_manager', '0007_auto_20170918_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotetranslationentry',
            name='translation_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='remote_translation_entry', to='translation_manager.TranslationEntry'),
        ),
    ]
